/**
 * Every shipped event script — the 863 scripts of disk files 186 and
 * 187 — with where it runs, what starts it, the save-state gate in front of
 * each start, and a verdict on whether it can be started on its own.
 *
 * GENERATED by scripts/build-event-data.mjs — do not hand-edit this file or
 * events.json beside it, which holds the rows. The verdicts and gates are the
 * output of a static walk over every event, map and NPC script read from the
 * USA disc; see /events/chains/ for what each column means.
 *
 * Gate notation: `flag N set` / `clear`, `flags N..M is V` (a run of flags
 * read as one number), `value N is V` / `not V` / `>= V` …, `state:…` for a
 * save-state test that is not a flag, `other:…` for a runtime test, and
 * `computed:…` for a value the launching script wrote itself before testing.
 */

export type EventVerdictClass =
  | 'standalone'
  | 'chained'
  | 'cosmetic'
  | 'map'
  | 'generic'
  | 'battle'
  | 'npc'
  | 'mid-chain'
  | 'unresolved'
  | 'in-battle';

export interface EventRecord {
  /** "402/1" — event file and script number, the way the scripts name them. */
  key: string;
  /** Event file id as the scripts pass it; disk-file-187 scripts carry bit 15. */
  file: number;
  script: number;
  /** Lives in disk file 187: a scripted-battle script, not a field cutscene. */
  inBattle: boolean;
  /** Display form of the key. */
  label: string;
  /** The event file's name from the community symbol table, if it has one. */
  fileName: string | null;
  /** The map the script loads into the displayed slot itself. */
  ownMap: number | null;
  /**
   * The map it runs on once inheritance is resolved. One entry normally;
   * several when it is launched from more than one map (a generic contact
   * event, a map-triggered event, an ambiguous inheritance); empty when it has
   * no map of its own and nothing to inherit from.
   */
  maps: number[];
  /** Parallel to maps: the map's name from the symbol table, or null. */
  mapNames: (string | null)[];
  mapResolution: string;
  /** Every start source: event predecessors, map scripts, contact scripts, battles, NPC scripts. */
  startedBy: string[];
  predecessors: string[];
  chainsTo: string[];
  /** Successors with the walked gate on each start: to[gate]{other}+stacked. */
  chainsToGuarded: string[];
  /** Maps whose init or story scripts launch this event. */
  launchMaps: number[];
  /** Maps whose contact scripts (100–199) launch this event. */
  contactMaps: number[];
  npcLaunchedBy: string[];
  npcGates: string[];
  npcGatesOther: string[];
  npcListGates: string[];
  postBattleFrom: string[];
  preBattleMaps: number[];
  battleMaps: number[];
  handsOffToMap: number[];
  preloadsForSuccessor: number[];
  /** The save-state gate on each map-side launch. */
  gates: string[];
  /** Runtime and computed conditions on those launches. */
  gatesOther: string[];
  gateNotes: string[];
  inheritedChars: number[];
  setupOnlyInDebug: string[];
  verdict: string;
  verdictClass: EventVerdictClass;
  reasons: string[];
  coldStart: string;
}

export const EVENT_VERDICT_LABELS: Record<EventVerdictClass, string> = {
  standalone: 'standalone',
  chained: 'chained, self-contained',
  cosmetic: 'chained, obi/music inherited',
  map: 'map-triggered',
  generic: 'generic contact event',
  battle: 'post-battle, inherits map',
  npc: 'NPC-launched, inherits map',
  'mid-chain': 'mid-chain',
  unresolved: 'unresolved root',
  'in-battle': 'in-battle script',
};

/** Event file ids in the order they appear. */
export const EVENT_FILES: number[] = [400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,554,561,600,601,602,603,604,605,606,650,651,652,653,654,655,656,657,658,659,660,700,701,702,703,704,705,706,707,708,750,751,752,753,754,755,756,757,758,759,760,800,801,803,804,805,806,807,808,809,810,811,32769,32770,32771,32772,32773,32774,32775];

export const EVENT_VERDICT_COUNTS: Record<EventVerdictClass, number> = {"standalone":331,"chained":141,"map":124,"npc":4,"unresolved":49,"cosmetic":127,"generic":34,"mid-chain":17,"battle":2,"in-battle":34};

// The rows, one JSON object per line in events.json. Loaded as text so the
// type checker does not infer a 863-element literal.
import raw from './events.json?raw';

export const EVENTS: EventRecord[] = JSON.parse(raw) as EventRecord[];
